### ISSUE TITLE
[Feature Request] Ability to extract (AD)PCM data from FMP, PMD and BTI instrument and banks

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#10]
I don't know if it is possible in a current state of this tool, but still - I would like to to be able to rip sample data from .BTI, .BTB, PVI, PPC, with further possibility to export it to .wav files and, if possible, edit like in BambooTracker

**Comment by rerrahkr** [comment]
It seems that at the moment there is no tool to manage (or edit) ADPCM samples for use in OPNA.
As this tool currently only handles FM voices, it may be developed as a separate tool, besides adding ADPCM editing capabilities.
