### ISSUE TITLE
[Linux/BSD] Make this tool installable to /usr/local/*

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#12]
Just like with Bamboo Tracker. Currently there are no rules for `make install` under Linux and, possibly, BSD.

**Comment by rerrahkr** [comment]
I don't have a linux machine currently, but this seems possible by adding the following lines.

```qmake
win32:target.path = C:/YM2608-Tone-Editor
else:target.path = /usr/local/bin
INSTALLS += target
```

Anyway I will open a new PR.
