### ISSUE TITLE
MUCOM88 parameters order

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#14]
Currently, when converting instrument to MUCOM88,  algorithm number precedes feedback level:
`@0:{
  4,   0`

Is that correct? I have found some [MUCOM88 mml files](https://github.com/0x6797/MUCOM88-MML/blob/master/001-Romancia/RO-001_Fanfare/RO-001.muc) that have these values the other way around. Also, other tools, such as OPN2 Bank Editor expect feedback level before ALG as well, so when the MUCOM text values produced by this tool are pasted into OPN-BE, the instrument ends up being incorrect.

**Comment by rerrahkr** [comment]
Thanks for your report. It was mistake, so I fixed it at bcfcfbc067ca56e14bd1ffe5815fe5289ca7d688.
This changes only the preset, so you need to fix the order of output parameter manually if formats.ini has been created.

**Comment by freq-mod** [comment]
Thank you!
