### ISSUE TITLE
Default MMLDRV output format is wrong

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/YM2608-Tone-Editor#15]
rerrahkr/BambooTracker#300 reported by @freq-mod

**Comment by rerrahkr** [comment]
Fixed at b5e4bca57914228cb741340a4675d53996f51027. Also you need to modify formats.ini if it exists.

**Comment by freq-mod** [comment]
Sorry for not giving any feedback, but it works now, thanks!
