### ISSUE TITLE
[Linux] No audio output

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#16]
`Using emulator: Nuked OPN-Mod`
`PulseAudioService: pa_context_connect() failed`
`using null output device, none available`

PulseAudio was installed, didn't help. BambooTracker works fine.

**Comment by rerrahkr** [comment]
Unlike BambooTracker, I use Qt multimedia in this project.
I don't have the environment at hand to replicate this, so I can't give a critical point, but I think the problem is either a library issue or a PulseAudio settings.

**Comment by OPNA2608** [comment]
Tested on Ubuntu 18.04 and Qt5.15.2, sound works fine for me.

**Comment by freq-mod** [comment]
Linux Mint 20.1 (essentially Ubuntu 20.04.1) ant Qt5 5.12.8, no sound with terminal output as in original post.

**Comment by freq-mod** [comment]
Changing sampling rate produces following error in terminal:
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1215, resource id: 12471584, major code: 40 (TranslateCoords), minor code: 0`

**Comment by OPNA2608** [comment]
Do other Qt GUI applications work with PA for you? Try running as `env PULSE_LOG=4 YM2608ToneEditor` and see if the additional logs spit out anything useful.

**Comment by freq-mod** [comment]
>Do other Qt GUI applications work with PA for you?

BambooTracker, I guess.

>Try running as env PULSE_LOG=4 YM2608ToneEditor and see if the additional logs spit out anything useful.

I'm sure what did you mean as the "addidtional logs", as I can't locate them anywhere, and terminal output says the same thing.

**Comment by freq-mod** [comment]
Fixed by installing` libqt5multimedia5-plugins`
