### ISSUE TITLE
VGI import bug (operators 2 and 3 swapped)

### ISSUE THREAD

**Issue by bryc** [rerrahkr/YM2608-Tone-Editor#21]
I tried to use this to convert VGI to OPNI (GENNY VST plugin saves VGI, TFI), but results were bad. Seems operators 2 and 3 are swapped.

Then I tried TFI format and it seemed correct, so maybe there some confusion on the order of operators 2 and 3?

**Comment by rerrahkr** [comment]
Thank you for your report. I fixed it in a9aa70045386ee2a487d866283ef7280b5695c74. Would you mind checking that [mod-bin.zip](https://github.com/rerrahkr/YM2608-Tone-Editor/files/10391965/mod-bin.zip) the fixed buid binary works as you intend?

**Comment by bryc** [comment]
I tested it, and it's correct now. I also checked original trackers of TFI and VGI, they also expect 1,2,3,4 order. Source of incorrect information for order of 1,3,2,4 seems to be: https://plutiedev.com/format-tfi

Thanks!
