### ISSUE TITLE
Enhancement: "Edit name" should remember current name

### ISSUE THREAD

**Issue by Phroneris** [rerrahkr/YM2608-Tone-Editor#24]
Currently, the "Edit name" button produces the "Edit tone name" dialog with an empty name field.
This field should be filled with the tone's current name so that it can be reused for renaming.

**Comment by rerrahkr** [comment]
ご意見ありがとうございます．  
feef8fe6d5a86435235376c80e0b89447df15bf9 で名前編集ダイアログを開いた直後は選択中のトーンの名前をデフォルト名として表示するよう修正いたしました．

**Comment by Phroneris** [comment]
v0.4.4にて確認できました。
ありがとうございました！
