### ISSUE TITLE
furnace instrument volume bug

### ISSUE THREAD

**Issue by damifortune** [rerrahkr/YM2608-Tone-Editor#25]
hello. for reasons beyond my comprehension, .fui conversions behave strangely in furnace - they do not respond to volume commands either in the pattern or in the form of volume macros. they will act at full volume no matter what

i had this issue in furnace version "0.6pre4hotfix" and updated to the latest "0.6pre5" just in case but it still happened. i was using tone editor v0.4.3 initially but i also updated to 0.4.4 to troubleshoot and still had the issue.

**Comment by damifortune** [comment]
ok, i am now aware that this is caused by the .fui instruments being saved with 'TL scaling' for all operators set to "NO" instead of "AUTO". so this is not as much of a bug as i thought, i apologize. it would be helpful if they were set to "AUTO" though by default. anyway you can close this if you want! sorry!

**Comment by defensem3ch** [comment]
@rerrahkr this can be closed per https://github.com/rerrahkr/YM2608-Tone-Editor/pull/27
