### ISSUE TITLE
Unable to build under Qt 5.12.9 and 64-bit MinGW [Win 10]

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#3]
Since 4cc479d I'm unable to build the tool.
output of make: https://gist.github.com/freq-mod/1cce63b16b43d0cd048f6ae6a2b5e77f

**Comment by rerrahkr** [comment]
Thanks for your report. There is a solution that [I create a new hash](https://stackoverflow.com/questions/48526115/using-qstring-as-the-key-in-stdunordered-map), but those errors are happened in only `class FileIo`, so I simply replaced the type of `std::unordered_map` key from `QString` with `std::string` at 422860ed5c2e94069e70ab2043b9329c07db3f3b.

**Comment by freq-mod** [comment]
I works now, thanks!

**Comment by freq-mod** [comment]
Again, since a565426 I'm unable to build this tool. `ff_io.cpp`, line 100 causes the problem I think.

https://pastebin.com/LLx1vMVL

**Comment by rerrahkr** [comment]
How about 2e1a059853ff950419c97797d80aaa8cbef0e2ac? I wonder why such an error does not occur in my environment.

**Comment by freq-mod** [comment]
Now it works. Also don't know why it happened.
