### ISSUE TITLE
Currently played note isn't displayed properly

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#4]
Very small and cosmetic, but:
When upper row of keyboard keys is used, notes higher than E aren't displayed correctly, only octave number is snown (for example, 5 rather than F5).

**Comment by rerrahkr** [comment]
Oops, I forgot to fix it when changing keyboard input method. I did at 0c4d0ae9ac90b88696782d532773cabc94831826, thanks for your report.

**Comment by freq-mod** [comment]
That one is fixed, thanks, yet I spotted one more weird thing - there is no octave 0 (well, there is, but it's actually octave 8, above octave 7 it loops back)

**Comment by rerrahkr** [comment]
I forgot why there is no octave 0, but I will add it later.
Octave 8 and above will not sound correctly because the chip pitch register overflows. Should I disable key-on?

**Comment by freq-mod** [comment]
Yes, and add octave 0, please.

**Comment by freq-mod** [comment]
Now everything is okay, thanks!
