### ISSUE TITLE
Banks-related issues

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#5]
1. I am unable to load .btb banks in other way than drag-and dropping them onto application windows (open bank file option let me to choose only .bti instruments)
2. When several instruments are loaded jamming keyboard becomes harder since instruments on the list are being changed after some key-ons.

**Comment by rerrahkr** [comment]
They were fixed by 32fb3e64fa007e90fcb01a450ee105bdc378a38b.

**Comment by freq-mod** [comment]
Thank you.
But yet I want to ask - given there is some kind of PSG support in this tool, would it be possible to add support for PSG instrument load from .bti/.btb?

**Comment by rerrahkr** [comment]
Unlike BambooTracker, there is no tick control routine in this editor. We can't run sequence data now, because BambooTracker's SSG instrument is supposed to be controlled by ticks. Since it would requires significant changes to the audio routine, I don't implement it for now.

**Comment by freq-mod** [comment]
Ah, I see. Thanks for the clarifying. That will wait, then.
