### ISSUE TITLE
Add support for PMD 4.8+ ver. (SSG-EG support)

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#6]
Work on PMD have recenltyl resumed, resulting in numerous features implemented - one of them is YM2608's SSG-EG.

Textual format tone structure is also different -  [newpmd.zip](https://github.com/rerrahkr/YM2608-Tone-Editor/files/5041411/newpmd.zip), also contains .bti ver of instrument 240

There are two versions of new format - in case of first, `-1` means SSG-EG dsabled and `0-7` mean type of envelope shape, while second: `0-7` mean SSG-EG disabled (internally: invalid envelope shape) and `8-15`mean the same as envelope type `0-7` of first version.

As for emulation, MAME 2608 is flawed. (although @jpcima once mentioned his potential fix: https://github.com/jpcima/BambooTracker/tree/mame-ssgeg)
There is also Nuked OPN-Mod, genpfm is allegedly just patched MAME 2612 FM core, redundant.

**Comment by rerrahkr** [comment]
Thanks for your request.
I often felt the need for SSG-EG during the development of BambooTracker and I planned to implement it in this project as well.

I learned the new format of PMD for the first time, but I can't find it in PMDMML.MAN the official manual. Where did you get that information?

About emulation core, there is still no perfect emulator, so I would like to add Nuked-OPN Mod because of its synthesis accuracy and portability to the project.

**Comment by freq-mod** [comment]
>I learned the new format of PMD for the first time, but I can't find it in PMDMML.MAN the official manual. Where did you get that information?

Well, 
- Masahiro Kajihara's Twitter and Youtube posts
- [this video](https://www.youtube.com/watch?v=hHOeqC6whto)
- https://twitter.com/i/status/1220130542353555456
- [this s98droid issue ticket](https://github.com/autch/s98droid/issues/2)

>there is still no perfect emulator, so I would like to add Nuked-OPN Mod because of its synthesis accuracy

Nuked-OPN has one insignificant flaw- there are leftovers from original code, related to YM2612-exclusive features (ch6 PCM), but aside from that, yeah, it's the best option

**Comment by rerrahkr** [comment]
I think the last `; 8`s are just comments to notify users of SSG-EG parameters. Focusing on MML channels, `SE` commands corresponding to these comments are set with the tone number commands, and this commands control the SSG-EG actually.

**Comment by freq-mod** [comment]
So it's just like hardware envelopes. Anyway I spotted something weird in a certain MML:
`@79` 4 7
 1 0 0 2 0 30 3 2 3 **3** 0
 13 2 0 7 3 0 0 4 3 **3** 0
 1 0 0 2 0 31 3 2 7 0 1
 12 2 0 7 3 0 0 4 7 0 0

What is the second-to-last column for? VOPM to PMD conversion leftover (DT2) or some different parameter?

**Comment by rerrahkr** [comment]
It's DT2. The instruments you send to me seems what you copy from the MML attached in the video, which has `#DT2Flag	On` that allow you set DT2 parameters in tone definitions. But there is no OPM flag in the compile option (`#Option		/v/c`), so MC will skip this parameter in the compilation.

**Comment by rerrahkr** [comment]
I added Nuked OPN-Mod at 420a15105666b1b47469af878563a31392676716 and SSG-EG sliders at 5fac2c8d3370deb28e460f4ef85bf7b27dfa5382.

**Comment by freq-mod** [comment]
There is a bug: when you have two instruments on a list, one affects the another when it comes to SSG-EG

**Comment by rerrahkr** [comment]
Ah, I forgot to change it, sorry. Fixed at b91417350b630e684b5ab9e2697359b2797075ce.

**Comment by freq-mod** [comment]
regarding (rerrahkr/BambooTracker#252):
>I also checked that VEDSE, the new tone editor of PMD supporting SSG-EG, exports a tone to MML with comments about SSG-EG value. At the moment there are few PMD tones using SSG-EG, however, it will be necessary to add the new text import format from PMD MML.

Are there plans to add it to Tone Editor as well?

**Comment by rerrahkr** [comment]
I implement SSG-EG edit as handling its value between 0 to 15, which helps me to add SSG-EG parser/exporter easily. I'll try it.

**Comment by rerrahkr** [comment]
Support from 2e1a059853ff950419c97797d80aaa8cbef0e2ac. To read SSGEG from a text, you have to manually modify the import format.

**Comment by freq-mod** [comment]
Thank you so much!
