### ISSUE TITLE
Add suport for more formats

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#7]
The only things I miss here are .FF, WOPN bank formats and .DMP, OPNI single instruments.

**Comment by rerrahkr** [comment]
Thanks for your request. If it is possible, I'll try to add export features not only import.

**Comment by rerrahkr** [comment]
Completed by 6c1d4a43cb95a8810f0f6d251f797571ec619232. You can also export a tone to .ff and .dmp.

**Comment by freq-mod** [comment]
Thanks! 
Is tone export to .opni/wopn imposible?

**Comment by rerrahkr** [comment]
I don't implement them now because I don't understand the detailed specifications especially .wopn, but I will try again if possible.

**Comment by freq-mod** [comment]
I've been thinking about some more obscure bank formats that are supported in OPN2 Bank Editor and if at least import can be implemented here:
GYB banks (.gyb)
GEMS banks (.bnk)

Specs and examples come with a source code.

**Comment by rerrahkr** [comment]
I added .wopn and .opni export by 39898f0e7a15a72adc08f1146500bcfc35fa99aa.

**Comment by freq-mod** [comment]
.wopn export doesn't work correctly - produced .wopn files can't be opened in OPN2 Bank Editor, throwing error about bad file format.

**Comment by rerrahkr** [comment]
> .wopn export doesn't work correctly

I fixed several lines in the source at c214018cbd070d5bfa0d192e8031b07b8949632a. Does it solve that?

**Comment by freq-mod** [comment]
It is still very glitchy, only 1 instrument is present as it should although it is grayed out, don't know why, thre rest is just garbage data repeated over and over
[ew3.zip](https://github.com/rerrahkr/YM2608-Tone-Editor/files/5084453/ew3.zip) - contain .FF file and wopn created out of it

**Comment by rerrahkr** [comment]
`WOPN_Init` is prepared in WOPN library, so I used it in export. At c00325b5737f9d97a9a1ff334efa8b0446d55ac9 unused instruments are zero-initialized and only blank instruments are grayed out.

**Comment by freq-mod** [comment]
I's better, there are no garbage data, but still there is only one instrument even when there are several in the instrument list

**Comment by rerrahkr** [comment]
Are you selecting only 1 instrument in bank export? Only the instruments selected in the list will be exported as a bank file. To export the entire list, you need to select all instruments.

**Comment by freq-mod** [comment]
Ah, right, sorry about that. It works fine, then

**Comment by rerrahkr** [comment]
Added .gyb and .bnk import at b21438f622ac8bc579ad7b5bec191409fe6c6bf2 and 03b02ff47a514467b9cdf082813efcfe8901938a. I doesn't implement export because this app cannot set the information required to generate these files.

**Comment by freq-mod** [comment]
Thanks a lot for all that work!
