### ISSUE TITLE
[Feature Request] Search Function

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/YM2608-Tone-Editor#8]
I have a very large bank, say 200 instruments. Ability to search single instrument by name would be useful.

**Comment by rerrahkr** [comment]
Thanks for your request, I'll try it.

**Comment by rerrahkr** [comment]
I added it at 24a21317c4575eb697ce4eb96f38f44fa3a62358.

**Comment by freq-mod** [comment]
Thank you!
